CREATE TABLE admin (
    id INT(11) NOT NULL AUTO_INCREMENT,
    UserName VARCHAR(100) NOT NULL,
    Password VARCHAR(100) NOT NULL,
    updationDate TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE tblauthors (
    AuthorId INT(11) NOT NULL AUTO_INCREMENT,
    AuthorName VARCHAR(255) NOT NULL,
    PRIMARY KEY (AuthorId)
);

CREATE TABLE tblcategory (
    CatId INT(11) NOT NULL AUTO_INCREMENT,
    CategoryName VARCHAR(255) NOT NULL UNIQUE,
    Status TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (CatId)
);

CREATE TABLE tblbooks (
    BookId INT(11) NOT NULL AUTO_INCREMENT,
    BookName VARCHAR(255) NOT NULL,
    CatId INT(11) NOT NULL,
    AuthorId INT(11) NOT NULL,
    ISBNNumber VARCHAR(50) NOT NULL UNIQUE,
    BookCount INT(11) NOT NULL DEFAULT 1,
    PRIMARY KEY (BookId),
    FOREIGN KEY (CatId) REFERENCES tblcategory(CatId) ON DELETE CASCADE,
    FOREIGN KEY (AuthorId) REFERENCES tblauthors(AuthorId) ON DELETE CASCADE
);

CREATE TABLE tblstudents (
    id INT(11) NOT NULL AUTO_INCREMENT,
    StudentId VARCHAR(7) NOT NULL UNIQUE,
    FullName VARCHAR(120) NOT NULL,
    MobileNumber VARCHAR(10) NOT NULL,
    EmailId VARCHAR(120) NOT NULL,
    Password VARCHAR(120) NOT NULL,
    Status INT(1) NOT NULL,
    RegDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdationDate TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE tblissuedbookdetails (
    id INT(11) NOT NULL AUTO_INCREMENT,
    StudentID VARCHAR(20) NOT NULL,
    BookId INT(11) NOT NULL,
    IssueDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (StudentID) REFERENCES tblstudents(StudentId) ON DELETE CASCADE,
    FOREIGN KEY (BookId) REFERENCES tblbooks(BookId) ON DELETE CASCADE
);